# Generated by Django 5.1.6 on 2025-03-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisElektronik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeGjl', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('jenis_elektronik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.jeniselektronik')),
            ],
        ),
        migrations.CreateModel(
            name='Kerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeRsk', models.CharField(max_length=10, unique=True)),
                ('nama_kerusakan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('jenis_elektronik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.jeniselektronik')),
            ],
        ),
    ]
