# Generated by Django 5.1.6 on 2025-03-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gejala', models.ManyToManyField(to='expert_system_app.gejala')),
                ('jenis_elektronik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.jeniselektronik')),
                ('kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.kerusakan')),
            ],
        ),
    ]
