# Generated by Django 5.1.6 on 2025-03-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0002_aturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akurasi', models.FloatField()),
                ('tanggal_diagnosa', models.DateTimeField(auto_now_add=True)),
                ('gejala', models.ManyToManyField(to='expert_system_app.gejala')),
                ('jenis_elektronik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.jeniselektronik')),
                ('kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.kerusakan')),
            ],
        ),
    ]
