# Generated by Django 5.1.6 on 2025-03-28 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0003_diagnosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan',
            name='akurasi',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='status',
            field=models.CharField(default='Selesai', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='akurasi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='kerusakan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.kerusakan'),
        ),
        migrations.CreateModel(
            name='Solusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_solusi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('biaya_perbaikan', models.PositiveIntegerField(default=0)),
                ('waktu_perbaikan', models.CharField(blank=True, max_length=50, null=True)),
                ('kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.kerusakan')),
            ],
        ),
    ]
