# Generated by Django 5.1.6 on 2025-03-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0004_aturan_akurasi_diagnosa_catatan_diagnosa_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aturan',
            name='akurasi',
        ),
    ]
