# Generated by Django 5.1.6 on 2025-03-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0005_remove_aturan_akurasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosa',
            name='solusi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
