# Generated by Django 5.1.6 on 2025-03-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0006_diagnosa_solusi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solusi',
            name='biaya_perbaikan',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='solusi',
            name='is_recommended',
            field=models.BooleanField(default=True),
        ),
    ]
