# Generated by Django 5.1.6 on 2025-03-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0009_alter_solusi_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturan',
            name='kerusakan_sebelumnya',
            field=models.ManyToManyField(blank=True, related_name='aturan_dari_kerusakan', to='expert_system_app.kerusakan'),
        ),
        migrations.AlterField(
            model_name='aturan',
            name='gejala',
            field=models.ManyToManyField(blank=True, to='expert_system_app.gejala'),
        ),
        migrations.AlterField(
            model_name='aturan',
            name='kerusakan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aturan_menuju_kerusakan', to='expert_system_app.kerusakan'),
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='akurasi',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='kerusakan',
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='kerusakan',
            field=models.ManyToManyField(blank=True, to='expert_system_app.kerusakan'),
        ),
    ]
