# Generated by Django 5.1.6 on 2025-03-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_system_app', '0010_aturan_kerusakan_sebelumnya_alter_aturan_gejala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosa',
            name='akurasi',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='kerusakan',
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='status',
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='solusi',
            field=models.TextField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiagnosaKerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akurasi', models.FloatField(default=0.0)),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa_kerusakan', to='expert_system_app.diagnosa')),
                ('kerusakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_system_app.kerusakan')),
            ],
            options={
                'unique_together': {('diagnosa', 'kerusakan')},
            },
        ),
    ]
